# codemagic.yaml

workflows:
  android-release-build:
    name: Android Release Build
    instance_type: linux  # This is the correct line
    max_build_duration: 60

    environment:
      groups:
        - android_signing 
      vars:
        PACKAGE_NAME: "com.expe"

    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Build Android release APK
        script: | 
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
