# codemagic.yaml
# FINAL VERSION - Adds execute permission to gradlew script.

workflows:
  android-release-build:
    name: Android Release Build
    max_build_duration: 60

    environment:
      groups:
        - android_signing 
      vars:
        PACKAGE_NAME: "com.freedevloper.budgetwise"

    scripts:
      - name: Install npm dependencies
        script: | 
          npm install

      - name: Build Android release APK
        script: | 
          cd android
          # Grant execute permission to the gradlew script
          chmod +x ./gradlew 
          # Now, run the build command
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
