# codemagic.yaml
# Clean build setup without extra packages

workflows:
  android-release-build:
    name: Android Release Build
    max_build_duration: 60

    environment:
      groups:
        - android_signing 
      vars:
        PACKAGE_NAME: "com.freedevloper.budgetwise"

    scripts:
      - name: Clean project and install dependencies
        script: |
          rm -rf node_modules android/.gradle android/build
          npm install
          cd android
          ./gradlew clean

      - name: Build Android release APK
        script: | 
          cd android
          chmod +x ./gradlew 
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
