# codemagic.yaml
# FINAL VERSION - Adds execute permission to gradlew script and fixes autolinking issue

workflows:
  android-release-build:
    name: Android Release Build
    max_build_duration: 60

    environment:
      groups:
        - android_signing 
      vars:
        PACKAGE_NAME: "com.freedevloper.budgetwise"

    scripts:
      - name: Install npm dependencies and generate autolinking
        script: |
          npm install
          npx react-native config

      - name: Build Android release APK
        script: | 
          cd android
          chmod +x ./gradlew 
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
