# codemagic.yaml
# This workflow builds a release APK for your React Native Android app.

workflows:
  android-release-build:
    name: Android Release Build
    instance_type: linux_x2  # A fast and cost-effective machine for Android builds
    max_build_duration: 30   # Optional: sets a 30-minute timeout for the build

    environment:
      # This group is essential. It tells Codemagic to use the keystore
      # you will set up in the Codemagic UI.
      groups:
        - android_signing 
      
      # Define environment variables for the signing process.
      # Codemagic will automatically populate these values from your 'android_signing' group.
      vars:
        PACKAGE_NAME: "com.freedevloper.budgetwise" # As defined in your app/build.gradle

    scripts:
      - name: Install npm dependencies
        script: | 
          npm install

      - name: Build Android release APK
        script: | 
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
