workflows:
  android-release-build:
    name: Android Release Build
    max_build_duration: 60

    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.budgetwisebare"

    scripts:
      - name: Clean and install dependencies
        script: |
          rm -rf node_modules android/.gradle android/build
          npm install
          cd android
          chmod +x ./gradlew
          ./gradlew clean
          cd ..

      - name: Inject static config to override RNGP autolinking check
        script: |
          echo '{
            "root": ".",
            "project": {
              "android": {
                "packageName": "'"$PACKAGE_NAME"'"
              }
            }
          }' > rn-config.json

          echo "require = function() { return require('./rn-config.json') }" > rn-inject.js

          export NODE_OPTIONS="--require $(pwd)/rn-inject.js"

      - name: Build Android release APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
